[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "interview_prep"
version = "0.1.0"
description = ""
authors = [{name = "Michael Kranzlein", email = "your.email@example.com"}]

[tool.pytest.ini_options]
testpaths = ["tests"]
